//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTv6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int MSG_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public string SUB { get; set; }
        public string SENDER { get; set; }
        public string TEXT { get; set; }
        public string ATTACHMENT { get; set; }
        public string RECEIVER { get; set; }
        public int STATUS { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
