//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTv6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class complain
    {
        public int cID { get; set; }
        public string sub { get; set; }
        public string OwnerID { get; set; }
        public string Text { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
