//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTv6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class complain
    {
        [Key]
        public int cID { get; set; }
        [Required(ErrorMessage = "Subject can not be empty."), StringLength(50)]
        public string sub { get; set; }
        public string OwnerID { get; set; }
        [Required(ErrorMessage = "Complain can not be empty.")]
        public string Text { get; set; }

        public virtual customer customer { get; set; }
    }
}
