//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTv6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_in
    {
        public string LID { get; set; }
        public int SID { get; set; }
        public string PASS { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual status status { get; set; }
    }
}
