//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTv6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class note
    {
        [Required(ErrorMessage = "Invalid Search")]
        public int NoteID { get; set; }

        [Required(ErrorMessage="*")]
        public string NoteName { get; set; }
        public string OwnerID { get; set; }
        [Required(ErrorMessage ="*")]
        public string Text { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
