//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTv6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class order
    {
        public int orderid { get; set; }
        public string prodid { get; set; }
        public int quant { get; set; }
        public double ammout { get; set; }
        public string stat { get; set; }
        public Nullable<System.DateTime> ord_date { get; set; }
        [Required]
        public string deliveryby { get; set; }
        public string orderby { get; set; }

        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
        public virtual product product { get; set; }
    }
}
