//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTv6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.orders = new HashSet<order>();
            this.sales = new HashSet<sale>();
        }
    
        public string PID { get; set; }
        public string P_NAME { get; set; }
        public string P_IMG { get; set; }
        public string TYPE { get; set; }
        public string AVAILABILITY { get; set; }
        [Required(ErrorMessage ="*")]
        public int QUANTITY { get; set; }
        public double BUY_PRICE { get; set; }
        [Required(ErrorMessage = "*"), Range(1, 99999999, ErrorMessage = "*")]
        public double SELL_PRICE { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> Add_PDate { get; set; }
    
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale> sales { get; set; }
    }
}
