//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTv6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int SLID { get; set; }
        public string PID { get; set; }
        public int QUANT { get; set; }
        public double OB_AMMOUNT { get; set; }
        public double PROFIT { get; set; }
        public string C_NAME { get; set; }
        public string C_MOB { get; set; }
        public string SOLD_BY { get; set; }
        public System.DateTime Sell_SDate { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual product product { get; set; }
    }
}
