USE [master]
GO
/****** Object:  Database [BusinessToolDB]    Script Date: 11/16/2020 4:06:18 PM ******/
CREATE DATABASE [BusinessToolDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BusinessToolDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BusinessToolDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BusinessToolDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BusinessToolDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BusinessToolDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BusinessToolDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BusinessToolDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BusinessToolDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BusinessToolDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BusinessToolDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BusinessToolDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [BusinessToolDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BusinessToolDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BusinessToolDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BusinessToolDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BusinessToolDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BusinessToolDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BusinessToolDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BusinessToolDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BusinessToolDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BusinessToolDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BusinessToolDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BusinessToolDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BusinessToolDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BusinessToolDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BusinessToolDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BusinessToolDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BusinessToolDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BusinessToolDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BusinessToolDB] SET  MULTI_USER 
GO
ALTER DATABASE [BusinessToolDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BusinessToolDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BusinessToolDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BusinessToolDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BusinessToolDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BusinessToolDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BusinessToolDB] SET QUERY_STORE = OFF
GO
USE [BusinessToolDB]
GO
/****** Object:  Table [dbo].[chats]    Script Date: 11/16/2020 4:06:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[chats](
	[MSG_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime2](0) NOT NULL,
	[SUB] [varchar](250) NULL,
	[SENDER] [varchar](50) NOT NULL,
	[TEXT] [varchar](max) NOT NULL,
	[ATTACHMENT] [varchar](300) NULL,
	[RECEIVER] [varchar](50) NOT NULL,
	[STATUS] [int] NOT NULL,
 CONSTRAINT [PK__chats__825DA51C17C6F92B] PRIMARY KEY CLUSTERED 
(
	[MSG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[complains]    Script Date: 11/16/2020 4:06:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[complains](
	[cID] [int] IDENTITY(1,1) NOT NULL,
	[sub] [varchar](50) NULL,
	[OwnerID] [varchar](50) NOT NULL,
	[Text] [varchar](max) NOT NULL,
 CONSTRAINT [PK__complain__D830D457DFE272A9] PRIMARY KEY CLUSTERED 
(
	[cID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[customers]    Script Date: 11/16/2020 4:06:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[customers](
	[cusid] [varchar](50) NOT NULL,
	[name] [varchar](100) NOT NULL,
	[design] [varchar](30) NOT NULL,
	[email] [varchar](50) NOT NULL,
	[mobile] [varchar](50) NOT NULL,
	[reg_date] [datetime2](0) NULL,
	[status] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[cusid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[employees]    Script Date: 11/16/2020 4:06:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[employees](
	[EmpID] [varchar](50) NOT NULL,
	[E_NAME] [varchar](50) NOT NULL,
	[DID] [int] NOT NULL,
	[SAL] [float] NOT NULL,
	[E_MOB] [varchar](14) NOT NULL,
	[E_MAIL] [varchar](50) NOT NULL,
	[JOIN_DATE] [datetime2](0) NOT NULL,
	[ADDED_BY] [varchar](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EmpID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[log_in]    Script Date: 11/16/2020 4:06:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[log_in](
	[LID] [varchar](50) NOT NULL,
	[SID] [int] NOT NULL,
	[PASS] [varchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[LID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[notes]    Script Date: 11/16/2020 4:06:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[notes](
	[NoteID] [int] IDENTITY(1,1) NOT NULL,
	[NoteName] [varchar](50) NULL,
	[OwnerID] [varchar](50) NOT NULL,
	[Text] [varchar](max) NOT NULL,
 CONSTRAINT [PK__notes__EACE357F70163F49] PRIMARY KEY CLUSTERED 
(
	[NoteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[notices]    Script Date: 11/16/2020 4:06:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[notices](
	[noticeID] [int] IDENTITY(1,1) NOT NULL,
	[noteSub] [varchar](100) NOT NULL,
	[noticetext] [varchar](max) NOT NULL,
 CONSTRAINT [PK__notices__4ED12E4E979D4467] PRIMARY KEY CLUSTERED 
(
	[noticeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[orders]    Script Date: 11/16/2020 4:06:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[orders](
	[orderid] [int] IDENTITY(1,1) NOT NULL,
	[prodid] [varchar](15) NOT NULL,
	[quant] [int] NOT NULL,
	[ammout] [float] NOT NULL,
	[stat] [varchar](50) NOT NULL,
	[ord_date] [datetime2](0) NULL,
	[deliveryby] [varchar](50) NOT NULL,
	[orderby] [varchar](50) NOT NULL,
 CONSTRAINT [PK__orders__080E37755F40D859] PRIMARY KEY CLUSTERED 
(
	[orderid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[products]    Script Date: 11/16/2020 4:06:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[products](
	[PID] [varchar](15) NOT NULL,
	[P_NAME] [varchar](50) NOT NULL,
	[P_IMG] [varchar](50) NULL,
	[TYPE] [varchar](20) NOT NULL,
	[AVAILABILITY] [varchar](20) NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[BUY_PRICE] [float] NOT NULL,
	[SELL_PRICE] [float] NOT NULL,
	[MOD_BY] [varchar](50) NOT NULL,
	[Add_PDate] [datetime2](0) NULL,
 CONSTRAINT [PK__products__C577552077360BE9] PRIMARY KEY CLUSTERED 
(
	[PID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[profile_images]    Script Date: 11/16/2020 4:06:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[profile_images](
	[UID] [varchar](50) NOT NULL,
	[IMAGE] [varchar](500) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[sales]    Script Date: 11/16/2020 4:06:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sales](
	[SLID] [int] IDENTITY(1,1) NOT NULL,
	[PID] [varchar](15) NOT NULL,
	[QUANT] [int] NOT NULL,
	[OB_AMMOUNT] [float] NOT NULL,
	[PROFIT] [float] NOT NULL,
	[C_NAME] [varchar](25) NOT NULL,
	[C_MOB] [varchar](14) NOT NULL,
	[SOLD_BY] [varchar](50) NOT NULL,
	[Sell_SDate] [datetime2](0) NOT NULL,
 CONSTRAINT [PK__sales__A43D35CF8823EBD3] PRIMARY KEY CLUSTERED 
(
	[SLID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[status]    Script Date: 11/16/2020 4:06:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[status](
	[SID] [int] NOT NULL,
	[DESIGNATION] [varchar](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[chats] ADD  CONSTRAINT [DF__chats__DATE__5070F446]  DEFAULT (getdate()) FOR [DATE]
GO
ALTER TABLE [dbo].[chats] ADD  CONSTRAINT [DF__chats__SUB__5165187F]  DEFAULT (NULL) FOR [SUB]
GO
ALTER TABLE [dbo].[chats] ADD  CONSTRAINT [DF__chats__ATTACHMEN__52593CB8]  DEFAULT (NULL) FOR [ATTACHMENT]
GO
ALTER TABLE [dbo].[customers] ADD  DEFAULT (getdate()) FOR [reg_date]
GO
ALTER TABLE [dbo].[employees] ADD  DEFAULT (getdate()) FOR [JOIN_DATE]
GO
ALTER TABLE [dbo].[log_in] ADD  DEFAULT (NULL) FOR [PASS]
GO
ALTER TABLE [dbo].[orders] ADD  CONSTRAINT [DF__orders__ord_date__5CD6CB2B]  DEFAULT (getdate()) FOR [ord_date]
GO
ALTER TABLE [dbo].[orders] ADD  CONSTRAINT [DF__orders__delivery__5DCAEF64]  DEFAULT (NULL) FOR [deliveryby]
GO
ALTER TABLE [dbo].[products] ADD  CONSTRAINT [DF__products__AVAILA__5FB337D6]  DEFAULT ('AVAILABLE') FOR [AVAILABILITY]
GO
ALTER TABLE [dbo].[products] ADD  CONSTRAINT [DF__products__Add_PD__60A75C0F]  DEFAULT (getdate()) FOR [Add_PDate]
GO
ALTER TABLE [dbo].[sales] ADD  CONSTRAINT [DF__sales__Sell_SDat__6383C8BA]  DEFAULT (getdate()) FOR [Sell_SDate]
GO
ALTER TABLE [dbo].[chats]  WITH CHECK ADD  CONSTRAINT [FK_chats_employees1] FOREIGN KEY([SENDER])
REFERENCES [dbo].[employees] ([EmpID])
GO
ALTER TABLE [dbo].[chats] CHECK CONSTRAINT [FK_chats_employees1]
GO
ALTER TABLE [dbo].[chats]  WITH CHECK ADD  CONSTRAINT [FK_chats_employees2] FOREIGN KEY([RECEIVER])
REFERENCES [dbo].[employees] ([EmpID])
GO
ALTER TABLE [dbo].[chats] CHECK CONSTRAINT [FK_chats_employees2]
GO
ALTER TABLE [dbo].[complains]  WITH CHECK ADD  CONSTRAINT [FK_complains_customers] FOREIGN KEY([OwnerID])
REFERENCES [dbo].[customers] ([cusid])
GO
ALTER TABLE [dbo].[complains] CHECK CONSTRAINT [FK_complains_customers]
GO
ALTER TABLE [dbo].[customers]  WITH CHECK ADD  CONSTRAINT [FK_customers_log_in] FOREIGN KEY([cusid])
REFERENCES [dbo].[log_in] ([LID])
GO
ALTER TABLE [dbo].[customers] CHECK CONSTRAINT [FK_customers_log_in]
GO
ALTER TABLE [dbo].[employees]  WITH CHECK ADD  CONSTRAINT [FK_employees_log_in1] FOREIGN KEY([EmpID])
REFERENCES [dbo].[log_in] ([LID])
GO
ALTER TABLE [dbo].[employees] CHECK CONSTRAINT [FK_employees_log_in1]
GO
ALTER TABLE [dbo].[employees]  WITH CHECK ADD  CONSTRAINT [FK_employees_log_in2] FOREIGN KEY([EmpID])
REFERENCES [dbo].[log_in] ([LID])
GO
ALTER TABLE [dbo].[employees] CHECK CONSTRAINT [FK_employees_log_in2]
GO
ALTER TABLE [dbo].[log_in]  WITH CHECK ADD  CONSTRAINT [FK_log_in_status] FOREIGN KEY([SID])
REFERENCES [dbo].[status] ([SID])
GO
ALTER TABLE [dbo].[log_in] CHECK CONSTRAINT [FK_log_in_status]
GO
ALTER TABLE [dbo].[notes]  WITH CHECK ADD  CONSTRAINT [FK_notes_employees] FOREIGN KEY([OwnerID])
REFERENCES [dbo].[employees] ([EmpID])
GO
ALTER TABLE [dbo].[notes] CHECK CONSTRAINT [FK_notes_employees]
GO
ALTER TABLE [dbo].[orders]  WITH CHECK ADD  CONSTRAINT [FK_orders_customers] FOREIGN KEY([orderby])
REFERENCES [dbo].[customers] ([cusid])
GO
ALTER TABLE [dbo].[orders] CHECK CONSTRAINT [FK_orders_customers]
GO
ALTER TABLE [dbo].[orders]  WITH CHECK ADD  CONSTRAINT [FK_orders_employees] FOREIGN KEY([deliveryby])
REFERENCES [dbo].[employees] ([EmpID])
GO
ALTER TABLE [dbo].[orders] CHECK CONSTRAINT [FK_orders_employees]
GO
ALTER TABLE [dbo].[orders]  WITH CHECK ADD  CONSTRAINT [FK_orders_products] FOREIGN KEY([prodid])
REFERENCES [dbo].[products] ([PID])
GO
ALTER TABLE [dbo].[orders] CHECK CONSTRAINT [FK_orders_products]
GO
ALTER TABLE [dbo].[products]  WITH CHECK ADD  CONSTRAINT [FK_products_employees] FOREIGN KEY([MOD_BY])
REFERENCES [dbo].[employees] ([EmpID])
GO
ALTER TABLE [dbo].[products] CHECK CONSTRAINT [FK_products_employees]
GO
ALTER TABLE [dbo].[profile_images]  WITH CHECK ADD  CONSTRAINT [FK_profile_images_employees] FOREIGN KEY([UID])
REFERENCES [dbo].[employees] ([EmpID])
GO
ALTER TABLE [dbo].[profile_images] CHECK CONSTRAINT [FK_profile_images_employees]
GO
ALTER TABLE [dbo].[sales]  WITH CHECK ADD  CONSTRAINT [FK_sales_employees] FOREIGN KEY([SOLD_BY])
REFERENCES [dbo].[employees] ([EmpID])
GO
ALTER TABLE [dbo].[sales] CHECK CONSTRAINT [FK_sales_employees]
GO
ALTER TABLE [dbo].[sales]  WITH CHECK ADD  CONSTRAINT [FK_sales_products] FOREIGN KEY([PID])
REFERENCES [dbo].[products] ([PID])
GO
ALTER TABLE [dbo].[sales] CHECK CONSTRAINT [FK_sales_products]
GO
USE [master]
GO
ALTER DATABASE [BusinessToolDB] SET  READ_WRITE 
GO
